apiVersion: v1
kind: Service
metadata:
  name: vote-ui-dev-svc
  namespace: default
spec:
  selector:
    app: vote-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80