name: UAT backend CI

on:
  push:
    tags:
      - '*'
    paths:
      - 'backend/src/main/java/**'
      - 'backend/pom.xml'
      - 'backend/Dockerfile'
      - 'backend/docker-entrypoint.sh'


env:
  IMAGE_NAME: yjring/vote-api
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  ACCESS_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  uat-backend-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Extract version
      id: extract_version
      run: echo "::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/})"
    
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: main
        token: ${{ secrets.MY_GITHUB_TOKEN }}
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven and generate reports
      run: mvn -B package --file backend/pom.xml

    - name: Test with Maven
      run: mvn test --file backend/pom.xml
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: backend/
        dockerfile: Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}

    - name: Update Kubernetes deployment
      run: |
         sed -i 's@image: .*@image: '"${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}"'@' ./deploy/uat/api-deployment.yaml


    - name: Commit changes
      run: |
        git pull
        git config --local user.email "PipelineBot"
        git config --local user.name "PipelineBot"
        git add ./deploy/uat/api-deployment.yaml
        git commit -m "Update backend image version to ${{ steps.extract_version.outputs.VERSION }}" -a
        git push 
